#!/bin/bash

echo "=> Building EasyLogin Web Admin"

docker run --rm -v $(pwd)/src:/EasyLoginWebAdmin -v /var/run/docker.sock:/var/run/docker.sock node bash -c "cd /EasyLoginWebAdmin && npm install && npm run build"

exit $?
